1. What does Pandas stand for?
* Panel Data or Python Data Analysis
2. What are the 2 collections used in Pandas?
* Series & Data Frames
3. Name 4 things Pandas can do for us.
* Pandas can load, manipulate, prepare, model, and analyze Data.
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
* inplace = True
5. What is a CSV?
* A simple way to store big data sets is to use CSV files (comma separated files). CSV files contains plain text and is a well know format that can be read by everyone including Pandas.
6. When cleaning data what values do we not like in our data?
* Null Data or Missing Data 


7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`

In [6]:
import numpy as np

arrayA= np.arange(12).reshape((2, 3, 2))

arrayA

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

In [7]:
import numpy as np

array = np.linspace(0, 20, num=6)

array

array([ 0.,  4.,  8., 12., 16., 20.])

9. Make a Deep Copy of the above array

In [18]:
import numpy as np

copyarray = array.copy

import copy

deepcopyarray = copy.deepcopy(array)

print(array)

print(deepcopyarray)

[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


10. Concatenate these 3 arrays into a new array named 'newArray'...
    ```python
            ([[25, 16]])
            ([[11, 2], [13, 4]])
            ([[7, 81], [5, 6], [11, 12]])

In [21]:
import numpy as np

arrayA = np.array([[25, 16]])
arrayB = np.array([[11, 2], [13, 4]])
arrayC = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA, arrayB, arrayC), axis=0)

newArray

array([[25, 16],
       [11,  2],
       [13,  4],
       [ 7, 81],
       [ 5,  6],
       [11, 12]])

11. Sort 'newArray' in order into 'sortedArray'

In [40]:
sortedArray = np.sort((newArray), axis=None)
sortedArray

array([ 2,  4,  5,  6,  7, 11, 11, 12, 13, 16, 25, 81])

 12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.

In [45]:
reshapedArray = sortedArray.reshape(4,3)

reshapedArray

Var1, Var2, Var3, Var4 = reshapedArray
print("a = ", Var1)
print("b = ", Var2)
print("c = ",Var3)
print("d = ", Var4)


a =  [2 4 5]
b =  [ 6  7 11]
c =  [11 12 13]
d =  [16 25 81]


13. Combined and sort the following arrays into one called 'comboArray' ...

    ```python
        one = ([10, 11, 12, 13, 14, 15, 16, 17])
        two = ([20, 21, 22, 23, 24, 25, 26, 27])
        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [54]:
array1 = np.array([10, 11, 12, 13, 14, 15, 16, 17])
array2 = np.array([20, 21, 22, 23, 24, 25, 26, 27])
array3 = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((array1, array2, array3), axis=0)
sortedcomboArray = np.sort((comboArray), axis=0)

sortedcomboArray

array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 11, 12, 13, 14, 15, 16, 17, 20,
       21, 22, 23, 24, 25, 26, 27])

14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving backward, every 5th element.

In [86]:
print('Sec1 = ', sortedcomboArray[1])
print('sec2 = ', sortedcomboArray [2:])
print('Sec3 =', sortedcomboArray [3:13])
print('Sec4 =', sortedcomboArray [-6:])
print('sec5 =',sortedcomboArray [-28:-10] )
print('sec6 = ', sortedcomboArray [16::2])
print('sec7 =', sortedcomboArray[27::-5] )

Sec1 =  1
sec2 =  [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
Sec3 = [ 3  4  5  6  7 10 11 12 13 14]
Sec4 = [22 23 24 25 26 27]
sec5 = [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
sec6 =  [20 22 24 26]
sec7 = [27 22 15 10  3]


15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object

In [91]:
import pandas as pd
import numpy as np

Ingredients =pd.Series(['Flour', "Milk", "Eggs", 'Spam'], name='Ingredients')
Quantity = pd.Series([4,1,2,1], name='Quantity')
Unit = pd.Series(['Cups', 'cup', 'lagre', 'can'], name='Unit')

# REMEMBER: axis 1 is -> columns

df = pd.concat([Ingredients, Quantity, Unit], axis=1)
df




Ingredients  Quantity   Unit
0       Flour         4   Cups
1        Milk         1    cup
2        Eggs         2  lagre
3        Spam         1    can

16. Take this data and create a DataFrame named studentData
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }

In [110]:
Name = pd.Series(['Jai', 'janusha', 'Gaurav', 'Anuj'], name='Name')
Height = pd.Series([5.1, 6.2, 5.1, 5.2], name='Height')
Qualifications = pd.Series(['Msc', 'MA', 'Msc', 'Msc'], name='Qualifications')
Address = pd.Series(['Delhi', 'Doha', 'Chennai', 'Dakhar'], name='Address')
Age = pd.Series ([21, 23, 24, 21], name='Age')
Pets = pd.Series(['Dog', 'Bunny', 'Chinchilla', 'Parrot'], name='Pets')
Sport = pd.Series (['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'], name ='Sports')

df = pd.concat ([Name, Height, Qualifications, Address, Age, Pets, Sport], axis=1)
df



data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }

df2 = pd.DataFrame(data)
df2

#RIP I did the entire first part without realziing I could import it easily >:(

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

17. Add a new column to the DataFrame with the following deserts:
        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [113]:
Deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

df.insert(7,'Deserts', Deserts, False)
df


Name  Height Qualifications  Address  Age        Pets          Sports  \
0      Jai     5.1            Msc    Delhi   21         Dog           Darts   
1  janusha     6.2             MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1            Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2            Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [115]:
df.sort_values(by=['Name', 'Address'], inplace = True)
df

Name  Height Qualifications  Address  Age        Pets          Sports  \
3     Anuj     5.2            Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1            Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1            Msc    Delhi   21         Dog           Darts   
1  janusha     6.2             MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

    ```python
        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

In [124]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('Cows_and_goats.csv')
df.to_csv(r'C:\Users\brianhaney\code\SavvyCoders\Homework\cows_and_goats.csv')  

20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [128]:

Vegetables = pd.Series(['Celery', 'Kale', 'Lettuce', 'Onion'], name='Veggies')
Price = pd.Series([2.27, 3.99, 2.99, 0.99], name='Veggie_Price')
Grocery_stores = pd.Series(['Publix', 'Walmart', 'Target', 'Wegmans'], name='Grocery_Stores')

df = pd.concat ([Vegetables, Price, Grocery_stores,], axis=1)
df.to_csv('Veggies.csv')
df.to_csv(r'C:\Users\brianhaney\code\SavvyCoders\Homework\Veggies.csv') 



Expires = ['one Day', 'Two Days', 'Three Days', 'Four Days']
df['Expires']=Expires
df.to_csv('NEWVeggies.csv')
df.to_csv(r'C:\Users\brianhaney\code\SavvyCoders\Homework\NEWVeggies.csv') 

 



